### ISSUE TITLE
Class definition ParallelFox.APPLICATION is not found

### ISSUE THREAD

**Issue by tuansieucap** [VFPX/ParallelFox#4]
I call StartWorkers function without passing the True value like this: Parallel.StartWorkers(FullPath("Steps_After.prg"))

I receive this error message: "Class definition ParallelFox.APPLICATION is not found".

I open ParallelFox.vcx file. I don't see APPLICATION function. How do we fix this issue?

**Comment by JoelLeach** [comment]
This error usually indicates that ParallelFox.exe has not been registered.  DO INSTALL to perform registration and see if that fixes the problem.  See https://github.com/VFPX/ParallelFox#installation for more details.

**Comment by tuansieucap** [comment]
Hello Joel,

Thank you for your response. I installed ParallelFox but encountered the
issue. I downloaded latest files on github. The problem was solved.

How do we run multiple commands or run some lines of codes using
ParallelFox? I use parallel.Docmd to run a line of code. I don't know how
to run some lines of codes.

Thank you,

Tuan

**Comment by JoelLeach** [comment]
Hi Tuan,

I'm glad to hear you resolved it.  Try Parallel.ExecScript() for running multiple lines of code.  Please note that there are training videos available on YouTube that cover the basics, as well as a Help file that is included with ParallelFox.  See https://github.com/VFPX/ParallelFox for more info.

**Comment by tuansieucap** [comment]
Hello Joel,

Thanks for your response. The script is running in a thread. After running
the lines of codes in the script, how do we get the values of variables in
the script?

Thank you,

Tuan

**Comment by tuansieucap** [comment]
Hello Joel,

Please disregard the previous email. I just figured it out. I pass _VFP to
ExecScript function. I use _VFP to execute commands. In the main process, I
see the variables in the ExecScript function. I call the ExecScript
function like this: Parallel.ExecScript(cScript,,_VFP).

Thank you,

Tuan

**Comment by JoelLeach** [comment]
It sounds like you are using _VFP as a manual callback from a worker to the main process. That might work, but you need to be careful you are not blocking other workers.  The ParallelFox way to return values from the worker to the main process is to use Worker Events.  Complete_After.prg is an example of this, but that would make more sense after you watch the training videos.
