### ISSUE TITLE
Help file is not showing content 

### ISSUE THREAD

**Issue by Terterola** [VFPX/ParallelFox#7]
Hi there,

There's something weird with the parallelfox.chm. When navigating the topics or searching the index, no content is shown, no matter the topic clicked, the content page keeps blank.

I tried to convert it to PDF and it worked well. It means the content is there. Anyway, I decided to comment here, maybe it's an important trick to someone else.

**Comment by fedesanp** [comment]
Hi,

This seems a locked file by system. When you download a file like .exe, .chm, or scripts the system locks them automatically. You have to manually unlock by right click on the file and check the unlocked option.

Regards.

**Comment by Terterola** [comment]
Ops, my fault! Tks! Feel free to delete this issue.

**Comment by JoelLeach** [comment]
Correct. This is Windows security behavior that has been around a long time. If Windows detects that a CHM file was downloaded, it will automatically block the content.  To fix, right-click on the CHM file, go to Properties, and there should be an Unblock button.
