### ISSUE TITLE
_Win64 not defined

### ISSUE THREAD

**Issue by DougHennig** [VFPX/ParallelFox#9]
I'm running ParallelFox 2.0 (distribution files from SWFox 2023) in VFPA in debug mode and am getting a "Variable '_WIN64' is not found" in WorkerProxy.Init when I call Parallel.StartWorkers. I have registered both ParallelFox.exe and ParallelFoxA.exe. What's weird is that as I step through the code in WorkerProxy.Init, the debugger shows that _Win64 is .F. so obviously it exists. I can type ? _WIN64 and it displays .F. But when I step over "Case Version(5) >= 1000 and _Win64 = .t.", it causes the error.

I know this is weird and might be specific to my environment so please don't spend a lot of time on this.

**Comment by JoelLeach** [comment]
Hi Doug,

I just tested in VFPA and got the same error.  I don't recall if I ran across that before, but an explicit COMPILE CLASSLIB parallelfox.vcx in VFPA fixed it for me.  The VCX must contain VFP9 compiled code, and I suppose VFPA doesn't know to recompile it automatically.

**Comment by DougHennig** [comment]
Thanks!
